---
api-core:
  project-id: zl-infra-main
  kms-project-id: zl-win-nodes
  front-end-base-url: https://zylitics.io
  cloud-kms:
    key-ring: zl-apps-auth-secret
    key: default-prod
    key-bucket: zl-secrets
  esdb:
    auth-user: elastic
    auth-user-secret-cloud-file: zl-esdb-auth.encrypt
    max-retries: 10
    shot-metadata-index: bt_shot_metadata
    zwl-program-output-index: zwl_program_output
    browser-index: browser
    env-var-host: ESDB_HOST # set using JIB to container's environment
  data-source:
    db-name: zbtp
    user-name: zbtp
    user-secret-cloud-file: zbtp-auth.encrypt
    # the private IP of instance, such as 10.11.12.9. CloudSql keeps the default 5432 port thus,
    # no need to mention that.
    private-host-cloud-file: zl-pgdb-private-host.encrypt
    # small idle connections because this app works for a single session only and mostly just one
    # thread will seek synchronous access to pgdb. see
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    min-idle-conn-pool: 2
  storage:
    # !! Note: remember to make a 'dev' version of all buckets and add them in other profiled yaml files.
    server-logs-bucket: zl-server-logs
    elem-shots-bucket: zl-elem-shots
    user-data-bucket: zl-user-data
    common-uploads-bucket: zl-common-uploads
    shot-bucket-au: zl-session-assets-au
    shot-bucket-tok: zl-session-assets-tok
    shot-bucket-hk: zl-session-assets-hk
    shot-bucket-mum: zl-session-assets-mum
    shot-bucket-eu: zl-session-assets-eu
    shot-bucket-uk: zl-session-assets-uk
    shot-bucket-la: zl-session-assets-la
    shot-bucket-slake: zl-session-assets-slake
    shot-bucket-usc: zl-session-assets-usc
    shot-bucket-nv: zl-session-assets-nv
    user-uploads-storage-dir-tmpl : USER_ID/uploads
    driver-logs-dir: driver-logs
    driver-logs-file: driver.log
    browser-perf-logs-dir: performance-logs
    browser-perf-logs-file: performance.log
    max-test-file-size-mb: 200
    max-common-file-size-mb: 100
  services:
    wzgp-endpoint: http://wzgp.api.internal.zylitics.io
    wzgp-version: beta
    wzgp-auth-user: prod-test
    wzgp-auth-secret-cloud-file: zl-wzgp-prod-test-auth.encrypt
    vm-machine-type: e2-standard-4
    vm-zones:
      - us-central1-c
      - us-west1-b
    btbr-version: beta
    btbr-port: 8080
    btbr-auth-user: root
    btbr-auth-secret-cloud-file: btbr-api-key.encrypted
    local-vm-env-var: VM_LOCAL
    sendgrid-api-key-secret-cloud-file: sendgrid-primary-mail-sender.encrypted
  email:
    issue-report-receiver: support@zylitics.io
    app-internal-email-sender: internal@zylitics.io
    no-reply-email-sender: noreply@zylitics.io
    email-beta-invite-tmp-id: d-283d2eb137f5409f8e8cc1337429319e
    email-team-invite-tmp-id: d-d836d47b1a4a460f978ff27d0dcdea71
    email-beta-welcome-tmp-id: d-4315d05c14b740ab9678da7273c109ec
    email-welcome-tmp-id: d-ab81d5d789e84570ad68e00884acb0c3
    email-change-tmp-id: d-9e208f6fe5ba4ab69d181cb3c3714d4b
    email-pwd-reset-tmp-id: d-d2787d44dd2742879c19dafc4cf10977
    email-verify-tmp-id: d-5cc358a3cc0d4b3faf9d1f487064ef47
    finish-signup-page: /finish-signup
    pwd-reset-page: /reset-pwd
    email-change-page: /change-email
    cta-link-tag: c2a_link
    marketing-email-group-id: 15323
    notification-email-group-id: 15319
---